version: '3.8'

services:
  postgres:
    image: postgres:15.2
    container_name: bloque-4-postgresql
    environment:
      POSTGRES_USER: salsaf003
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: salsaf003
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres_data: